#!/usr/bin/env node
/**
 * Re-mirrors multipart3d.com into ./site and patches it for offline use.
 *
 * Run this again whenever the website is updated (the bundle filenames are
 * content-hashed, so a plain file-by-file refresh would go stale).
 *
 *   node tools/sync-site.mjs
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SITE = path.join(ROOT, 'site');
const ORIGIN = 'https://www.multipart3d.com';

// drei's built-in "city" environment preset lives on a third-party CDN.
const DREI_HDRI_BASE =
  'https://raw.githack.com/pmndrs/drei-assets/456060a26bbeb8fdf79326f224b6d99b8bcce736/hdri/';
const HDRI_FILES = ['potsdamer_platz_1k.hdr'];

// troika-three-text (used for the 3D labels) resolves fonts through this CDN
// at runtime. Mirror the data it needs so labels render with no internet.
const FONT_CDN =
  'https://cdn.jsdelivr.net/gh/lojjic/unicode-font-resolver@v1.0.1/packages/data';
const FONT_FILES = [
  'codepoint-index/plane0/0-ff.json',
  'font-meta/latin.json',
  // Weights the UI is known to use, plus neighbours in case a style changes.
  ...[100, 200, 300, 400, 500, 600, 700, 800, 900].flatMap((w) => [
    `font-files/latin/sans-serif.normal.${w}.woff`,
    `font-files/latin/sans-serif.italic.${w}.woff`,
  ]),
];

// Files that are referenced from HTML/CSS rather than from the JS bundle.
const ROOT_FILES = [
  'index.html',
  'favicon.ico',
  'favicon-16x16.png',
  'favicon-32x32.png',
  'apple-touch-icon.png',
  'og.png',
  'logo-official.png',
  'robots.txt',
];

let downloaded = 0;
let skipped = 0;

const MESH_HOOK_FROM = 'this.isMesh=!0';
const MESH_HOOK_TO = 'this.isMesh=!0,globalThis.__mp3dMesh||(globalThis.__mp3dMesh=this)';

// Diagnostics only: publishing the camera lets tools project world positions to
// screen coordinates, which is how the profiler finds the cut gizmo to drag.
const CAM_HOOK_FROM = 'this.isPerspectiveCamera=!0';
const CAM_HOOK_TO = 'this.isPerspectiveCamera=!0,globalThis.__mp3dCamera=this';

// Diagnostics only: the scene is the reliable entry point for traversal.
// (__mp3dMesh is whatever Mesh was constructed first, typically an empty
// helper with no position attribute and no parent.)
const SCENE_HOOK_FROM = 'this.isScene=!0';
const SCENE_HOOK_TO = 'this.isScene=!0,globalThis.__mp3dScene=this';
const INSTALL_SNIPPET =
  '\n;import("/mp3d-bvh.js").then(m=>m.install({verbose:false})).catch(e=>console.warn("mp3d-bvh:",e));\n';

/**
 * Suppresses the "Welcome" and "Enjoy your multipart!" dialogs by pre-setting
 * the app's OWN localStorage flags, so it simply believes they were already
 * dismissed. No DOM hacking and no React patching.
 *
 * The flag values are read out of the bundle rather than hardcoded: the intro
 * is gated on a revision string that upstream bumps to re-show it, and a stale
 * hardcoded value would silently let the dialog back in.
 */
async function writePrefsSeed(src) {
  const varOf = (key) => {
    const m = src.match(new RegExp('(\\w+)=`' + key.replace('.', '\\.') + '`'));
    return m ? m[1] : null;
  };

  const introKey = 'm3d.introSeenRevision';
  const thanksKey = 'm3d.thanksHidden';
  const introVar = varOf(introKey);
  const thanksVar = varOf(thanksKey);

  // Intro: openIntroIfUnseen does `getter() !== '<revision>'`
  const introRev = (src.match(/openIntroIfUnseen:\(\)=>\{\w+\(\)!==`([^`]+)`/) || [])[1];
  // Thanks: suppressed when getItem(key) === '<value>'
  const thanksVal = thanksVar
    ? (src.match(new RegExp('getItem\\(' + thanksVar + '\\)===`([^`]+)`')) || [])[1]
    : undefined;

  if (!introVar || !thanksVar || !introRev || !thanksVal) {
    throw new Error(
      'Could not read dialog-suppression flags from the bundle:\n' +
        `  ${introKey} var=${introVar} revision=${introRev}\n` +
        `  ${thanksKey} var=${thanksVar} value=${thanksVal}\n` +
        'The upstream app changed. Re-check tools/sync-site.mjs writePrefsSeed().'
    );
  }

  const contents = `/* Generated by tools/sync-site.mjs - do not edit. */
/* Marks the Welcome and "Enjoy your multipart!" dialogs as already dismissed. */
(function () {
  try {
    localStorage.setItem(${JSON.stringify(introKey)}, ${JSON.stringify(introRev)});
    localStorage.setItem(${JSON.stringify(thanksKey)}, ${JSON.stringify(thanksVal)});
  } catch (e) {
    /* localStorage unavailable: dialogs will simply show as normal. */
  }
})();
`;
  await fs.writeFile(path.join(SITE, 'mp3d-prefs.js'), contents);

  // Must run before the app module. A classic script executes immediately,
  // whereas module scripts are deferred, so head placement is enough.
  const indexPath = path.join(SITE, 'index.html');
  let html = await fs.readFile(indexPath, 'utf8');
  if (!html.includes('mp3d-prefs.js')) {
    html = html.replace('</head>', '    <script src="/mp3d-prefs.js"></script>\n  </head>');
    await fs.writeFile(indexPath, html);
  }

  console.log(`  dialogs suppressed via ${introKey}=${introRev}, ${thanksKey}=${thanksVal}`);
}

// Extra printers to add to the built-in list, keyed on the entry they should
// follow (must match exactly once in the bundle).
const EXTRA_PRINTERS = [
  {
    after: '{id:`anycubic-kobra3`,brand:`Anycubic`,model:`Kobra 3`,buildVolume:{x:250,y:250,z:260}}',
    entry: '{id:`anycubic-kobras1max`,brand:`Anycubic`,model:`Kobra S1 Max`,buildVolume:{x:350,y:350,z:350}}',
  },
  {
    // Flashforge is a new brand section, inserted after Elegoo and before
    // Voron to keep the existing alphabetical brand order.
    after: '{id:`elegoo-neptune4pro`,brand:`Elegoo`,model:`Neptune 4 Pro`,buildVolume:{x:225,y:225,z:265}}',
    entry:
      '{id:`flashforge-ad5x`,brand:`Flashforge`,model:`AD5X`,buildVolume:{x:220,y:220,z:220}},' +
      '{id:`flashforge-creator5`,brand:`Flashforge`,model:`Creator 5`,buildVolume:{x:256,y:256,z:256}}',
  },
];

/**
 * Publishes the app's zustand stores on globalThis for src/mp3d-autocut.js:
 *   __mp3dCutStore      parts, cut mode, connectors, history (the cut engine)
 *   __mp3dPrinterStore  selected printer and build volume (side panel)
 *
 * Located by their initial state rather than by minified name, and each must
 * match exactly once. `a=globalThis.x=create(...)` is still a single
 * initialiser, so the declarations keep working unchanged.
 */
function patchStores(src) {
  const specs = [
    ['__mp3dCutStore', '((e,t)=>({isManifoldReady:!1'],
    ['__mp3dPrinterStore', '((e,t)=>({selectedPresetId:'],
  ];
  let out = src;
  for (const [name, init] of specs) {
    if (out.includes(`globalThis.${name}=`)) continue;
    const esc = init.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    // `init` already starts with the create() call's own "(".
    const re = new RegExp(`\\b(\\w+)=(\\w+)${esc}`, 'g');
    const hits = [...out.matchAll(re)];
    if (hits.length !== 1) throw new Error(`store patch: expected 1 match for ${name}, found ${hits.length}`);
    const [whole, varName, create] = hits[0];
    out = out.replace(whole, `${varName}=globalThis.${name}=${create}${init}`);
    console.log(`  exposed ${name} (${varName})`);
  }
  return out;
}

function patchPrinterList(src) {
  let out = src;
  for (const { after, entry } of EXTRA_PRINTERS) {
    if (out.includes(entry)) continue; // already present after a previous run
    const occurrences = out.split(after).length - 1;
    if (occurrences !== 1) {
      throw new Error(`printer list patch: expected anchor once, found ${occurrences}: ${after.slice(0, 60)}...`);
    }
    out = out.replace(after, `${after},${entry}`);
    const model = (entry.match(/model:`([^`]+)`/) || [])[1] || entry;
    console.log(`  added printer: ${model}`);
  }
  return out;
}

/**
 * Makes 3MF export keep per-triangle paint (see src/mp3d-color-export.js).
 *
 * Minified names change on every upstream build, so everything is located by
 * shape rather than by name, and every edit must match exactly the expected
 * number of times or sync throws. A silently half-applied patch here would
 * mean colours quietly disappearing again.
 */
function patchColorExport(src) {
  // 1. The per-part 3MF writer: async function YD(geom,xform,color){let r=GD(geom,xform),i=new ST.default;return i.file(`[Content_Types].xml`,...
  const writerRe =
    /async function (\w+)\((\w+),(\w+),(\w+)\)\{let (\w+)=(\w+)\(\2,\3\),(\w+)=new (\w+)\.default;return \7\.file\(`\[Content_Types\]\.xml`/g;
  const writers = [...src.matchAll(writerRe)];
  if (writers.length !== 1) throw new Error(`colour export: expected 1 3MF writer, found ${writers.length}`);
  const [whole, writer, g, x, c, , toVerts, , jszip] = writers[0];

  const hookedWriter = whole.replace(
    `async function ${writer}(${g},${x},${c}){`,
    `async function ${writer}(${g},${x},${c},__p){` +
      `if(__p&&__p.slotLabels&&globalThis.__mp3dExport3mf)try{` +
      `return await globalThis.__mp3dExport3mf({geometry:${g},transform:${x},color:${c},part:__p,toVerts:${toVerts},JSZip:${jszip}.default})` +
      `}catch(__e){console.warn("[mp3d-color] colour export failed, using stock export:",__e)}`
  );
  let out = src.replace(whole, hookedWriter);

  // 2. Every call site passes the part through as a 4th argument.
  //    Part objects: W(n.geometry,n.transform,fC(n)??n.color)
  //    Zip items:    W(n.geometry,n.transform,n.color)  (items gain .part below)
  const callRe = new RegExp(
    `\\b${writer}\\((\\w+)\\.geometry,\\1\\.transform,((?:\\w+\\(\\1\\)\\?\\?)?\\1\\.color)\\)`,
    'g'
  );
  const calls = out.match(callRe) || [];
  if (calls.length !== 3) throw new Error(`colour export: expected 3 writer call sites, found ${calls.length}`);
  out = out.replace(callRe, `${writer}($1.geometry,$1.transform,$2,$1.part||$1)`);

  // 3. The multi-part zip builds plain items from parts; carry the part along.
  const itemRe = /(\{geometry:(\w+)\.geometry,transform:\2\.transform,filename:[^{}]*?,color:\w+\(\2\)\?\?\2\.color)\}/g;
  const items = out.match(itemRe) || [];
  if (items.length !== 1) throw new Error(`colour export: expected 1 zip item builder, found ${items.length}`);
  out = out.replace(itemRe, '$1,part:$2}');

  // 4. The painted-3MF importer receives the JSZip; remember it so export can
  //    reuse the source project's filament settings.
  const importerRe = /async function (\w+)\((\w+)\)\{let (\w+)=new DOMParser,(\w+)=await (\w+)\(\2,\3\);/g;
  const importers = [...out.matchAll(importerRe)];
  if (importers.length !== 1) throw new Error(`colour export: expected 1 3MF importer, found ${importers.length}`);
  const [imp, impName, zipArg] = importers[0];
  out = out.replace(imp, imp.replace(`async function ${impName}(${zipArg}){`, `async function ${impName}(${zipArg}){globalThis.__mp3dSrcZip=${zipArg};`));

  // 5. Publish the writer's vertex converter and zip library for the
  //    multi-plate project export. Guarded, and JSZip resolved lazily, so a
  //    scoping change upstream can only disable project export, never the app.
  out +=
    `\n;try{globalThis.__mp3dExportApi={toVerts:${toVerts},get JSZip(){return ${jszip}.default}}}` +
    `catch(__e){console.warn("[mp3d-project] export api unavailable:",__e)}\n`;

  console.log(`  patched colour export: writer ${writer}, 3 call sites, importer ${impName}`);
  return out;
}

/**
 * Finds the entry module and applies the two raycast-acceleration edits.
 * Throws if the anchors are missing, so a silent regression is impossible
 * after an upstream update.
 */
async function patchBundle() {
  // Our own code lives outside site/ because sync wipes that directory.
  await fs.copyFile(path.join(ROOT, 'src', 'mp3d-bvh.js'), path.join(SITE, 'mp3d-bvh.js'));

  const assetsDir = path.join(SITE, 'assets');
  const files = (await fs.readdir(assetsDir)).filter((f) => f.endsWith('.js'));

  let target = null;
  for (const f of files) {
    const src = await fs.readFile(path.join(assetsDir, f), 'utf8');
    if (src.includes(MESH_HOOK_FROM)) {
      target = { file: f, src };
      break;
    }
  }

  if (!target) {
    throw new Error(
      'Raycast patch anchor "this.isMesh=!0" not found in any bundle file.\n' +
        'three.js may have been minified differently upstream. Re-check\n' +
        'site/mp3d-bvh.js before shipping, or the app will just run unpatched.'
    );
  }

  const occurrences = target.src.split(MESH_HOOK_FROM).length - 1;
  if (occurrences !== 1) {
    throw new Error(`Expected exactly 1 mesh hook anchor, found ${occurrences} in ${target.file}`);
  }

  let out = target.src.replace(MESH_HOOK_FROM, MESH_HOOK_TO);

  for (const [from, to, what] of [
    [CAM_HOOK_FROM, CAM_HOOK_TO, 'camera'],
    [SCENE_HOOK_FROM, SCENE_HOOK_TO, 'scene'],
  ]) {
    if (out.includes(from)) out = out.replace(from, to);
    else console.warn(`  WARNING: ${what} hook anchor missing; gizmo profiling will not work`);
  }

  if (!out.includes('mp3d-bvh.js')) out += INSTALL_SNIPPET;

  out = patchColorExport(out);
  out = patchPrinterList(out);
  out = patchStores(out);

  await fs.writeFile(path.join(assetsDir, target.file), out);
  console.log(`  patched ${target.file}: mesh hook + BVH install snippet`);

  // Our classic scripts: colour exporter (must be ready before any export)
  // and the repair UI (only activates inside the desktop app).
  const indexPath = path.join(SITE, 'index.html');
  let html = await fs.readFile(indexPath, 'utf8');
  for (const name of ['mp3d-color-export.js', 'mp3d-repair-ui.js', 'mp3d-autocut.js', 'mp3d-plates.js']) {
    await fs.copyFile(path.join(ROOT, 'src', name), path.join(SITE, name));
    if (!html.includes(name)) {
      const tag = name === 'mp3d-color-export.js' ? `<script src="/${name}"></script>` : `<script src="/${name}" defer></script>`;
      html = html.replace('</head>', `    ${tag}\n  </head>`);
    }
  }
  await fs.writeFile(indexPath, html);

  await writePrefsSeed(target.src);
}

async function save(url, dest) {
  const res = await fetch(url);
  if (!res.ok) {
    console.warn(`  skip ${url} -> HTTP ${res.status}`);
    skipped++;
    return false;
  }
  await fs.mkdir(path.dirname(dest), { recursive: true });
  await fs.writeFile(dest, Buffer.from(await res.arrayBuffer()));
  downloaded++;
  return true;
}

function unique(list) {
  return [...new Set(list)];
}

async function main() {
  console.log(`Mirroring ${ORIGIN} -> ${SITE}`);
  await fs.rm(SITE, { recursive: true, force: true });
  await fs.mkdir(SITE, { recursive: true });

  // 1. Root files, including the entry HTML.
  for (const f of ROOT_FILES) await save(`${ORIGIN}/${f}`, path.join(SITE, f));

  const html = await fs.readFile(path.join(SITE, 'index.html'), 'utf8');

  // 2. Build assets referenced from index.html.
  const htmlAssets = unique(
    [...html.matchAll(/(?:src|href)="(\/assets\/[^"]+)"/g)].map((m) => m[1])
  );
  for (const a of htmlAssets) await save(ORIGIN + a, path.join(SITE, a));

  // 3. Assets referenced from inside the build output (lazy chunks, wasm,
  //    workers, images, video). Repeat until no new references appear.
  const seen = new Set(htmlAssets);
  const queue = [...htmlAssets];
  const EXT = 'js|mjs|wasm|css|png|jpe?g|webp|svg|mp4|webm|gif|ico|woff2?|hdr';
  // Absolute public paths ("/logo.png", "/assets/x.wasm") and bundle-relative
  // asset paths ("assets/x.js") emitted by the bundler.
  const patterns = [
    new RegExp(`["'\`](/[A-Za-z0-9._/-]+\\.(?:${EXT}))["'\`]`, 'g'),
    new RegExp(`["'\`](assets/[A-Za-z0-9._-]+\\.(?:${EXT}))["'\`]`, 'g'),
  ];

  while (queue.length) {
    const current = queue.shift();
    if (!/\.(js|mjs|css)$/.test(current)) continue;
    let text;
    try {
      text = await fs.readFile(path.join(SITE, current), 'utf8');
    } catch {
      continue;
    }
    for (const re of patterns) {
      for (const m of text.matchAll(re)) {
        const ref = m[1].startsWith('/') ? m[1] : '/' + m[1];
        if (seen.has(ref)) continue;
        seen.add(ref);
        if (await save(ORIGIN + ref, path.join(SITE, ref))) queue.push(ref);
      }
    }
  }

  // 4. Third-party environment map, so lighting works with no internet.
  for (const f of HDRI_FILES) await save(DREI_HDRI_BASE + f, path.join(SITE, 'hdri', f));

  // 5. Font data for the 3D text labels.
  for (const f of FONT_FILES) await save(`${FONT_CDN}/${f}`, path.join(SITE, 'fontdata', f));

  // 6. Install the raycast acceleration (see site/mp3d-bvh.js for why).
  //
  // Two edits to the bundle:
  //   a) three.js's Mesh constructor publishes the first instance it creates,
  //      which is how mp3d-bvh.js reaches Mesh.prototype without a THREE
  //      global (the bundle exposes none, and r3f's scene lives in its own
  //      React reconciler tree that the DOM cannot reach).
  //   b) a dynamic import at the end of the module installs the patch.
  await patchBundle();

  // 7. Repoint the HDRI base URL at the local mirror.
  //
  // The font CDN URL is deliberately left alone: it is fetched from inside a
  // blob-URL worker where a root-relative path cannot resolve, so main.js
  // redirects that request to the local server at runtime instead.
  const rewrites = [[DREI_HDRI_BASE, '/hdri/', 'HDRI environment']];
  const hits = new Map(rewrites.map(([, , label]) => [label, 0]));

  for (const f of await fs.readdir(path.join(SITE, 'assets'))) {
    if (!f.endsWith('.js')) continue;
    const p = path.join(SITE, 'assets', f);
    let src = await fs.readFile(p, 'utf8');
    let changed = false;
    for (const [from, to, label] of rewrites) {
      if (!src.includes(from)) continue;
      src = src.split(from).join(to);
      hits.set(label, hits.get(label) + 1);
      changed = true;
    }
    if (changed) await fs.writeFile(p, src);
  }

  console.log(`\nDone. ${downloaded} files downloaded, ${skipped} skipped.`);
  for (const [label, n] of hits) {
    if (n > 0) console.log(`  rewrote ${label} URL to local path`);
    else
      console.warn(
        `  WARNING: ${label} URL not found in the bundle. The site may have ` +
          `changed; that feature will need an internet connection.`
      );
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
